pool:
  vmImage: ubuntu-16.04
#Your build pipeline references an undefined variable named ‘Parameters.RestoreBuildProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.RestoreBuildProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

steps:
  - task: UseDotNet@2
    displayName: 'Use .Net Core sdk 3.0.100'
    inputs:
      version: 3.0.100

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(Parameters.RestoreBuildProjects)'

  - task: richardfennellBM.BM-VSTS-Versioning-Task.Version-DotNetCoreAssemblies-Task.VersionDotNetCoreAssemblies@2
    displayName: 'Version .NET Core Assemblies'
    inputs:
      VersionRegex: '\d+\.\d+\.\d+'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(Parameters.RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: pack
    inputs:
      command: pack
      versioningScheme: byBuildNumber

  - task: DotNetCoreCLI@2
    displayName: Push
    inputs:
      command: push
      publishVstsFeed: 'ac341a44-b4a6-4161-9338-421eea2875bc'
    enabled: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
